dist: trusty
sudo: required

language: ruby

env:
  global:
  - DOCKER_IMAGE=goodeggs/docker-squash:latest
  - secure: "Gfx5WzQV0L0kG3utpJ3AIAR2YQRSqG8yKyRxwd29qM2M1c7LcGGRUaZ699IO2ouRKnoaMCUSPXPllPdtsykFmG/H1AM83TDKrCz2R+CSKmQoFJVFJo4eFIa1u7/Teymj7j3uIvPCw7kX1n9eVYKvbS7hMjkGAY+L5gry1CiYdEBeE1RcdEWqzYER/FMFDqtfKJSPOtiz4O3onRypkWzi5EglfBcOO3Ek4/fWls/M+b0C0Vk1HdyreF0YW8CUF+tij8iCI0zhbQB4DcSboVQMVacdYcRKtCTvYACNd5kanLIr6WVsYAM4G+QsQnHMg3y0A9QRGJRt8nVCUa+lMnf9hMGeFM1Obd5ScxzGh+5xfVLURHD5wqoD8jeJrUz0H2hfRiiA1lOEx6qje/8lcaCuwH0Xavqo6N2Py2gIHKWlos9TLzaiqENlW7aPumlhrrzRJqIWNX2oOnjZRj7tbItdENvRWC5GeIU5aWz8y5PgvsRRNJUBVghZpgzPkWCyjVYit/gmhkje33Gr0O6ueWQRNQ5gbo8y0vbjLA/W1m/1wkGmqUolQr2Iy92VGtVr/YvLL5Nd9/rLaTW3qmYapaugxPlk19VFJZasJDysBNbAxDgSoQX6QyGA/Ldi1cr5tEyj1DinKRC5Mm+pZusPhHZrIXOl/MDbXB2NFHij+e9IkVA=" # DOCKER_USER
  - secure: "6FhIGuElXHzxb+MfKrTg5bzHG0aVFl08U24BAoiCrjbXzN2a+9o4nhKL6RhP3CEBOwIBgjcXmJbP9U2U3CqlVavuzYE+6YE7fqtLhHxKsWUAU9qJq58mLkqiBPBozlvdW3+EvrBj0Hhb1faPqtnQcCL/Gpid1ioSlcJLX/4w/gmTPw41YM6pNzxdJtAYsg5qzq0RvuVJtjA9w2bDde+dwFtKTLqsMJw0H8SOqG4Ra5HZ5CE2T0TopxB70LTG45XfQ8CPNMU8/rCZS2i5qa0yFKe6Pr0h80Vbv9wRk6M9VvTDiU1fW7QCwJfF+SY2p0+RDOH8tMa8HSxPW/LuTM0pXczpSRb1vQrjdYWPQdGRMlyI3k2jDo/c3pPnLRK1Fu3GFxuvzl2R1IH/W2EwOfjPfR4DlyF8X5ALd81PEEbvymIbBkmgdFQAGL9Od7dvVhMl8UvVXK8maZXDFl+tWX6HxMwmkt/sYMDFar76NOzDtzQbKAZHnu1MZsaY7X+efbnswo3tl8NOjzdu4P8KjrgReANS4hZ4PcHESe1kQS1O2ToT3/bKLC3fFvGfS6hQlSi2sOGw+LpJ0IB8vuRkgjvlZjhQUHmsZ/XWQp9TYtnvS82dKbx1Njmg4GA4OzMWImBoK2CNVZ836SZkyVXpDHXVVAm5+nt/8L154OmhHSTdC+4=" # DOCKER_PASS

install: true # skip

before_script: docker build -t "$DOCKER_IMAGE" .

script: docker run -ti "$DOCKER_IMAGE" --version

before_deploy: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

deploy:
  provider: script
  script: docker push "$DOCKER_IMAGE"
  on:
    branch: master

